on:
    push:
        branches: [main]
permissions:
    id-token: write # Required for OIDC
    contents: read
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: pnpm/setup@v3
              with:
                  version: 12
                  install: false
            - run: pnpm publish --provenance --recursive # Publish recursively to not fail if version already published
